title: "Knutmans Oracle & PL/SQL Blog"
description: "Tipps, Best Practices und Anleitungen zu Oracle Database, pl/sql und parallelisierung."
url: "https://knutman.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

locale: de
markdown: kramdown
highlighter: rouge

minimal_mistakes_skin: "default"
